name: Daily Football Analysis

on:
  schedule:
    - cron: '0 1 * * *'   # Exécution chaque jour à 01h UTC
  workflow_dispatch:       # Permet de lancer manuellement

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GROQ_API_KEY1: ${{ secrets.GROQ_API_KEY1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 numpy

      - name: Run daily football script
        run: python Analyse.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Daily update $(date)"
          git push
